def count_word_freq(doc):
    freq = {}
    words = [word.lower() for word in doc.split(' ') if word.isalpha()]
    for word in words:
        freq[word] = 1 + freq.get(word, 0)
    
    max_word = ''
    max_count = 0
    for (w, c) in freq.items():
        if c > max_count:
            max_word = w
            max_count = c
    return (max_word, max_count)

if __name__ == '__main__':
    doc = """
    Hash tables are a type of data structure in which the address or the index value of the data element is generated from a hash function. That makes accessing the data faster as the index value behaves as a key for the data value. In other words Hash table stores key-value pairs but the key is generated through a hashing function. So the search and insertion function of a data element becomes much faster as the key values themselves become the index of the array which stores the data.
    In Python, the Dictionary data types represent implementation of hash tables. The Keys in the dictionary satisfy the following requirements.
    The keys of the dictionary are hashable i.e. the are generated by hashing function which generates unique result for each unique value supplied to the hash function.
    The order of data elements in a dictionary is not fixed.
    So we see the implementation of hash table by using the dictionary data types as below.
    """
    freq = count_word_freq(doc)
    print(freq)